<?php
return array(
        'ltv'=>array(
            'time'=>'日期',
            'channel'=>'渠道',
            'num'=>'注册人数',
            'one_amountfloat'=>'1天充值金额',
            'one_ltvfloat' =>'一天ltv',
            'three_amountfloat'=>'3天充值金额',
            'three_ltvfloat'=>'三天ltv',
            'seven_amountfloat'=>'7天充值金额',
            'seven_ltvfloat'=>'7天ltv',
            'fifteen_amountfloat'=>'15天充值金额',
            'fifteen_ltvfloat'=>'15天ltv',
            'twentyone_amountfloat'=>'21天充值金额',
            'twentyone_ltvfloat'=>'21天ltv',
            'thirty_amountfloat'=>'30充值金额',
            'thirty_ltvfloat'=>'30ltv',
            'fortyfive_amountfloat'=>'45天充值金额',
            'fortyfive_ltvfloat'=>'45天ltv',
            'sixty_amountfloat'=>'60天充值金额',
            'sixty_ltvfloat'=>'60天ltv',
        ),
        'base'=>array(
            'time'=>'日期',
            'channel'=>'渠道',
            'game'=>'区服',
            'newuser_num'=>'新注册人数',
            'login_num'=>'活跃玩家',
            'pay_sum'=>'总充值',
            'pay_num'=>'付费人数',
            'newpay_sum'=>'当日新增充值金额',
            'newpay_num'=>'当日新增付费人数',
            'prvar'=>'付费率',
            'arpu'=>'ARPU',
            'arppu'=>'ARPPU',
            'one_liucun'=>'一日留存',
            'two_liucun'=>'二日留存',
            'three_liucun'=>'三日留存',
            'four_liucun'=>'四日留存',
            'five_liucun'=>'五日留存',
            'six_liucun'=>'六日留存',
            'seven_liucun'=>'七日留存',
            'ten_liucun'=>'10日留存',
            'fifteen_liucun'=>'15日留存',
            'twentone_liucun'=>'21日留存',
            'thirty_liucun'=>'30日留存',
        ),
        'ltvtime'=>'2018-01-24 17:05:02',
        'basetime'=>'2018-01-24 17:07:16',


);
