<?php
return array(
    'appstore' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_ios',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'nd' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_iosnd',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'i4' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_iosi4',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'iapple' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_iosiiapple',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'itools' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_iosits',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'ky' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_iosky',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'pp' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_iospp',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'tbt' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_iostbt',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'tj' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_iostj',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'xx' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_iosxx',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'xy' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_iosxy',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
    'hmw' => array (
        'hostname' => '123.59.44.152',
        'database' => 'PayCenter_ioshmw',
        'username' => 'sg',
        'password' => 'f3%DEc*io7',
        'tablepre' => '',
        'charset' => 'utf8',
        'type' => 'mysqlx',
        'debug' => true,
        'pconnect' => 0,
        'autoconnect' => 0
        ),
);
