<?php
return array(
//'nd' => array('name' => '百度', 'servers' => array('1' => '百度_1区','2' => '百度_2区','3' => '百度_3区','4' => '百度_4区','5' => '百度_5区','6' => '百度_6区','7' => '百度_7区','8' => '百度_8区')),
//'i4' => array('name' => '爱思', 'servers' => array('1' => '爱思_1区','2' => '爱思_2区','3' => '爱思_3区','4' => '爱思_4区','5' => '爱思_5区','6' => '爱思_6区','7' => '爱思_7区','8' => '爱思_8区')),
//'iapple' => array('name' => '爱苹果', 'servers' => array('1' => '爱苹果_1区','2' => '爱苹果_2区','3' => '爱苹果_3区','4' => '爱苹果_4区','5' => '爱苹果_5区','6' => '爱苹果_6区','7' => '爱苹果_7区','8' => '爱苹果_8区')),
//'itools' => array('name' => 'ITOOLS', 'servers' => array('1' => 'ITOOLS_1区','2' => 'ITOOLS_2区','3' => 'ITOOLS_3区','4' => 'ITOOLS_4区','5' => 'ITOOLS_5区','6' => 'ITOOLS_6区','7' => 'ITOOLS_7区','8' => 'ITOOLS_8区')),
//'ky' => array('name' => '快用', 'servers' => array('1' => '快用_1区','2' => '快用_2区','3' => '快用_3区','4' => '快用_4区','5' => '快用_5区','6' => '快用_6区','7' => '快用_7区','8' => '快用_8区')),
//'pp' => array('name' => 'PP', 'servers' => array('1' => 'PP_1区','2' => 'PP_2区','3' => 'PP_3区','4' => 'PP_4区','5' => 'PP_5区','6' => 'PP_6区','7' => 'PP_7区','8' => 'PP_8区')),
//'tbt' => array('name' => '同步推', 'servers' => array('1' => '同步推_1区','2' => '同步推_2区','3' => '同步推_3区','4' => '同步推_4区','5' => '同步推_5区','6' => '同步推_6区','7' => '同步推_7区','8' => '同步推_8区')),
//'tj' => array('name' => '天机', 'servers' => array('1' => '天机_1区','2' => '天机_2区','3' => '天机_3区','4' => '天机_4区','5' => '天机_5区','6' => '天机_6区','7' => '天机_7区','8' => '天机_8区')),
//'xx' => array('name' => 'XX', 'servers' => array('1' => 'XX_1区','2' => 'XX_2区','3' => 'XX_3区','4' => 'XX_4区','5' => 'XX_5区','6' => 'XX_6区','7' => 'XX_7区','8' => 'XX_8区')),
//'xy' => array('name' => 'XY', 'servers' => array('1' => 'XY_1区','2' => 'XY_2区','3' => 'XY_3区','4' => 'XY_4区','5' => 'XY_5区','6' => 'XY_6区','7' => 'XY_7区','8' => 'XY_8区')),
//'hmw' => array('name' => '海马玩', 'servers' => array('1' => '海马玩_1区','2' => '海马玩_2区','3' => '海马玩_3区','4' => '海马玩_4区','5' => '海马玩_5区','6' => '海马玩_6区','7' => '海马玩_7区','8' => '海马玩_8区')),

//'iossgqxzq' => array('table'=>'appstore','name' => '三国群雄再起', 'servers' => array('1' => 'iossgqxzq_1区','2' => 'iossgqxzq_2区','3' => 'iossgqxzq_3区','4' => 'iossgqxzq_4区','5' => 'iossgqxzq_5区','6' =>'iossgqxzq_6区', '7' => 'iossgqxzq_7区', '8' => 'iossgqxzq_8区', '9' => 'iossgqxzq_9区', '10' => 'iossgqxzq_10区', '11' => 'iossgqxzq_11区', '12' => 'iossgqxzq_12区', '13' => 'iossgqxzq_13区', '14' => 'iossgqxzq_14区')),

//'ioslztx' => array('table'=>'appstore','name' => '战乱天下', 'servers' => array('1' => 'ioslztx_1区','2' => 'ioslztx_2区','3' => 'ioslztx_3区','4' => 'ioslztx_4区','5' => 'ioslztx_5区','6' => 'ioslztx_6区','7' => 'ioslztx_7区','8' => 'ioslztx_8区','9' => 'ioslztx_9区','10' => 'ioslztx_10区','11' => 'ioslztx_11区','12' => 'ioslztx_12区','13' => 'ioslztx_13区','14' => 'ioslztx_14区')),
//'iossnqyz' => array('table'=>'appstore','name' => '少年群英志', 'servers' => array('1' => 'iossnqyz_1区','2' => 'iossnqyz_2区','3' => 'iossnqyz_3区','4' => 'iossnqyz_4区','5' => 'iossnqyz_5区','6' => 'iossnqyz_6区','7' => 'iossnqyz_7区','8' => 'iossnqyz_8区','9' => 'iossnqyz_9区','10' => 'iossnqyz_10区','11' => 'iossnqyz_11区','12' => 'iossnqyz_12区','13' => 'iossnqyz_13区','14' => 'iossnqyz_14区')),
'txiosdcn' => array('table'=>'appstore','name' => '天下三国', 'servers' => array('1' => 'iostxsg_1区','2' => 'iostxsg_2区','3' => 'iostxsg_3区','4' => 'iostxsg_4区','5' => 'iostxsg_5区','6' => 'iostxsg_6区','7'
 => 'iostxsg_7区','8' => 'iostxsg_8区','9' => 'iostxsg_9区','10' => 'iostxsg_10区','11' => 'iostxsg_11区','12' => 'iostxsg_12区','13' => 'iostxsg_13区','14' => 'iostxsg_14区')),
//'ioswzyx' => array('table'=>'appstore','name' => '王者英雄', 'servers' => array('1' => 'ioswzyx_1区','2' => 'ioswzyx_2区','3' => 'ioswzyx_3区','4' => 'ioswzyx_4区','5' => 'ioswzyx_5区','6' => 'ioswzyx_6区','7' => 'ioswzyx_7区','8' => 'ioswzyx_8区','9' => 'ioswzyx_9区','10' => 'ioswzyx_10区','11' => 'ioswzyx_11区','12' => 'ioswzyx_12区','13' => 'ioswzyx_13区','14' => 'ioswzyx_14区')),
'txiosbcn' => array('table'=>'appstore','name' => '三国玩战记', 'servers' => array('1' => 'iossglsyx_1区','2' => 'iossglsyx_2区','3' => 'iossglsyx_3区','4' => 'iossglsyx_4区','5' => 'iossglsyx_5区','6' => 'iossglsyx_6区','7' => 'iossglsyx_7区','8' => 'iossglsyx_8区','9' => 'iossglsyx_9区','10' => 'iossglsyx_10区','11' => 'iossglsyx_11区','12' => 'iossglsyx_12区','13' => 'iossglsyx_13区','14' => 'iossglsyx_14区')),
//'iosyhcs' => array('table'=>'appstore','name' => '英雄传说', 'servers' => array('1' => 'iosyhcs_1区','2' => 'iosyhcs_2区','3' => 'iosyhcs_3区','4' => 'iosyhcs_4区','5' => 'iosyhcs_5区','6' => 'iosyhcs_6区','7' => 'iosyhcs_7区','8' => 'iosyhcs_8区','9' => 'iosyhcs_9区','10' => 'iosyhcs_10区','11' => 'iosyhcs_11区','12' => 'iosyhcs_12区','13' => 'iosyhcs_13区','14' => 'iosyhcs_14区')),
'iosrrsg' => array('table'=>'third','name' => '人人三国IOS', 'servers' => array('1' => 'iosrrsg_1区','2' => 'iosrrsg_2区','3' => 'iosrrsg_3区','4' => 'iosrrsg_4区','5' => 'iosrrsg_5区','6' => 'iosrrsg_6区','7' => 'iosrrsg_7区','8' => 'iosrrsg_8区','9' => 'iosrrsg_9区','10' => 'iosrrsg_10区','11' => 'iosrrsg_11区','12' => 'iosrrsg_12区','13' => 'iosrrsg_13区','14' => 'iosrrsg_14区')),
'andrrsg' => array('table'=>'txandht','name' => '人人三国安卓', 'servers' => array('1' => 'andrrsg_1区','2' => 'andrrsg_2区','3' => 'andrrsg_3区','4' => 'andrrsg_4区','5' => 'andrrsg_5区','6' => 'andrrsg_6区','7' => 'andrrsg_7区','8' => 'andrrsg_8区','9' => 'andrrsg_9区','10' => 'andrrsg_10区','11' => 'andrrsg_11区','12' => 'andrrsg_12区','13' => 'andrrsg_13区','14' => 'andrrsg_14区')),
);
